 - name: cluster prep 1
   hosts: admin:worker
   become: true
   tasks: 
    - name: containerd remove
      pacman:
        name:
          - containerd
          - kubelet-bin
          - kubeadm-bin
          - kubectl-bin
          - fakeroot
          - devtools
        state: removed
        update_cache: no
