 - name: cluster prep 2
   hosts: admin:worker
   become: yes
   tasks: 
    - user: name=archie

    - lineinfile:
        path: /etc/sudoers.d/archie-allow-to-sudo-pacman
        state: present
        line: "archie ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        validate: /usr/sbin/visudo -cf %s
        create: yes